openapi: 3.0.3
info:
  version: 1.0.0
  title: Specification for Saleor-Akeneo PIM integration Lambda

security:
  - apiKeyAuth: []

paths:
  /v1/system/ping:
    get:
      operationId: ping
      summary: Replies with pong
      description: Replies ping with pong
      tags:
        - System
      security: []
      responses:
        "200":
          description: Pong
          content:
            text/plain:
              schema:
                type: string

  /v1/importProducts:
    post:
      operationId: importProducts
      summary: Imports Products
      description: Imports Products from Akeneo PIM to Saleor
      tags:
        - ImportProducts
      responses:
        "200":
          description: Product import operation was successfull
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Success"
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  
  /v1/registerApp:
    post:
      operationId: registerAppWithSaleor
      summary: Receives App Auth Token
      description: Receives POST request from Saleor containing App Auth Token
      tags:
        - RegisterApp
      requestBody:
        $ref: "#/components/requestBodies/AuthToken"
      responses:
        "200":
          description: App Auth Token successfully received
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
    
  requestBodies:
    AuthToken:
      content:
        application/json;charset=utf-8:
          schema:
            $ref: "#/components/schemas/AuthToken"

  schemas:
    Error:
      type: object
      description: Error object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    
    Success:
      type: object
      description: Success object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    
    AuthToken:
      type: object
      description: Saleor App Auth Token object
      required:
        - auth_token
      properties:
        auth_token:
          type: string